name: Test OIDC

on:
  push:
    branches:
      - jesserockz-2025-514

jobs:
  test:
    name: Publish to Espressif
    runs-on: ubuntu-latest
    environment: espressif
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Debug OIDC Claims
        uses: steve-todorov/oidc-debugger-action@f9915fe9dc64133704c072eb59436373c23e9fdd # v1.0.1
        with:
          audience: 'https://components.espressif.com'
